Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 16

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

